name: Codecov

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Install dependencies
        run: yarn

      - name: Generate coverage report
        run: yarn test --coverage

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v1
