name: Codecov

on: pull_request

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate coverage report
      run: yarn test --coverage
